# Generated by Django 5.2.6 on 2025-09-11 16:29

import common.models.auth
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', common.models.auth.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_tye',
        ),
    ]
