# Generated by Django 5.2.6 on 2025-09-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_managers_rename_user_type_user_user_tye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_tye',
            new_name='user_type',
        ),
    ]
